In [1]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

In [2]:
from ultralytics import YOLO
model = YOLO("yolo11n.pt")
results = model.train(
    data="coco8.yaml", 
    epochs=1, 
    imgsz=640,
    # Disable data augmentation
    hsv_h=0.0,  # HSV-Hue augmentation (fraction)
    hsv_s=0.0,  # HSV-Saturation augmentation (fraction)
    hsv_v=0.0,  # HSV-Value augmentation (fraction)
    degrees=0.0,  # Image rotation (+/- deg)
    translate=0.0,  # Image translation (+/- fraction)
    scale=0.0,  # Image scale (+/- gain)
    shear=0.0,  # Image shear (+/- deg)
    perspective=0.0,  # Image perspective (+/- fraction), range 0-0.001
    flipud=0.0,  # Image flip up-down (probability)
    fliplr=0.0,  # Image flip left-right (probability)
    mosaic=0.0,  # Mosaic augmentation (probability)
    mixup=0.0,  # Mixup augmentation (probability)
    copy_paste=0.0,  # Copy-paste augmentation (probability)
    erasing=0.0,  # Random erasing augmentation (probability)
    crop_fraction=1.0,  # Image crop fraction (range 0-1.0, 1.0=no crop)
)

New https://pypi.org/project/ultralytics/8.3.233 available  Update with 'pip install -U ultralytics'
WARNING 'crop_fraction' is deprecated and will be removed in in the future.
Ultralytics 8.3.184  Python-3.13.5 torch-2.9.0+cu130 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine\trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco8.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=1, erasing=0.0, exist_ok=False, fliplr=0.0, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.0, hsv_s=0.0, hsv_v=0.0, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=0.0

train: Scanning D:\00.MOTHER_BOXES\code\datasets\coco8\labels\train.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|█


val: Fast image access  (ping: 0.00.0 ms, read: 512.0126.4 MB/s, size: 54.0 KB)


val: Scanning D:\00.MOTHER_BOXES\code\datasets\coco8\labels\val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|█████


Plotting labels to D:\00.MOTHER_BOXES\code\modification\runs\detect\train7\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to D:\00.MOTHER_BOXES\code\modification\runs\detect\train7
Starting training for 1 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


        1/1     0.709G      1.301      2.191      1.621         13        640: 100%|██████████| 1/1 [00:03<00:00,  3.36

Epoch 1: cls_distill_loss_epoch=0.000000, dfl_distill_loss_epoch=0.000000, box_reg_distill_loss_epoch=0.000000



                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<0


                   all          4         17      0.586       0.85      0.849      0.631

1 epochs completed in 0.002 hours.
Optimizer stripped from D:\00.MOTHER_BOXES\code\modification\runs\detect\train7\weights\last.pt, 5.5MB
Optimizer stripped from D:\00.MOTHER_BOXES\code\modification\runs\detect\train7\weights\best.pt, 5.5MB

Validating D:\00.MOTHER_BOXES\code\modification\runs\detect\train7\weights\best.pt...
Ultralytics 8.3.184  Python-3.13.5 torch-2.9.0+cu130 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
YOLO11n summary (fused): 100 layers, 2,616,248 parameters, 0 gradients


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<0


                   all          4         17      0.586       0.85      0.849      0.631
                person          3         10      0.574        0.6      0.598      0.266
                   dog          1          1      0.554          1      0.995      0.697
                 horse          1          2      0.589          1      0.995      0.674
              elephant          1          2      0.372        0.5      0.518      0.257
              umbrella          1          1      0.574          1      0.995      0.995
          potted plant          1          1      0.855          1      0.995      0.895
Speed: 2.6ms preprocess, 43.8ms inference, 0.0ms loss, 2.3ms postprocess per image
Results saved to D:\00.MOTHER_BOXES\code\modification\runs\detect\train7


i saved the batch from the model to investigate the output here its name is my_dict.pkl

In [3]:
model.names

{0: 'person',
 1: 'bicycle',
 2: 'car',
 3: 'motorcycle',
 4: 'airplane',
 5: 'bus',
 6: 'train',
 7: 'truck',
 8: 'boat',
 9: 'traffic light',
 10: 'fire hydrant',
 11: 'stop sign',
 12: 'parking meter',
 13: 'bench',
 14: 'bird',
 15: 'cat',
 16: 'dog',
 17: 'horse',
 18: 'sheep',
 19: 'cow',
 20: 'elephant',
 21: 'bear',
 22: 'zebra',
 23: 'giraffe',
 24: 'backpack',
 25: 'umbrella',
 26: 'handbag',
 27: 'tie',
 28: 'suitcase',
 29: 'frisbee',
 30: 'skis',
 31: 'snowboard',
 32: 'sports ball',
 33: 'kite',
 34: 'baseball bat',
 35: 'baseball glove',
 36: 'skateboard',
 37: 'surfboard',
 38: 'tennis racket',
 39: 'bottle',
 40: 'wine glass',
 41: 'cup',
 42: 'fork',
 43: 'knife',
 44: 'spoon',
 45: 'bowl',
 46: 'banana',
 47: 'apple',
 48: 'sandwich',
 49: 'orange',
 50: 'broccoli',
 51: 'carrot',
 52: 'hot dog',
 53: 'pizza',
 54: 'donut',
 55: 'cake',
 56: 'chair',
 57: 'couch',
 58: 'potted plant',
 59: 'bed',
 60: 'dining table',
 61: 'toilet',
 62: 'tv',
 63: 'laptop',
 64: 'mou

In [4]:
import pickle

# Open the pickle file in binary read mode ('rb')
with open('my_dict.pkl', 'rb') as file:
    batch = pickle.load(file)

# Now 'data' contains the Python object that was saved
print(batch.keys())

dict_keys(['batch_idx', 'bboxes', 'cls', 'im_file', 'img', 'ori_shape', 'resized_shape'])


In [5]:
batch["batch_idx"], batch["batch_idx"].shape

(tensor([0., 1., 1., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]),
 torch.Size([24]))

In [6]:
batch["im_file"], 
# batch["im_file"].shape

(('E:\\00.MOTHER_BOXES\\code\\modification\\datasets\\coco8\\images\\train\\000000000034.jpg',
  'E:\\00.MOTHER_BOXES\\code\\modification\\datasets\\coco8\\images\\train\\000000000009.jpg',
  'E:\\00.MOTHER_BOXES\\code\\modification\\datasets\\coco8\\images\\train\\000000000030.jpg',
  'E:\\00.MOTHER_BOXES\\code\\modification\\datasets\\coco8\\images\\train\\000000000025.jpg'),)

In [7]:
batch["batch_idx"], batch["batch_idx"].shape

(tensor([0., 1., 1., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]),
 torch.Size([24]))

In [8]:
batch["img"], batch["img"].shape

(tensor([[[[0.5804, 0.5686, 0.4902,  ..., 0.5176, 0.5020, 0.4588],
           [0.4588, 0.5137, 0.4431,  ..., 0.4824, 0.5176, 0.4784],
           [0.3961, 0.4824, 0.4667,  ..., 0.4745, 0.5529, 0.5294],
           ...,
           [0.4824, 0.4824, 0.4824,  ..., 0.4824, 0.4824, 0.4824],
           [0.4824, 0.4824, 0.4824,  ..., 0.4824, 0.4824, 0.4824],
           [0.4824, 0.4824, 0.4824,  ..., 0.4824, 0.4824, 0.4824]],
 
          [[0.6902, 0.6824, 0.6039,  ..., 0.6471, 0.6314, 0.5765],
           [0.5686, 0.6235, 0.5686,  ..., 0.6039, 0.6431, 0.6000],
           [0.4980, 0.5882, 0.5725,  ..., 0.5961, 0.6784, 0.6510],
           ...,
           [0.4824, 0.4824, 0.4824,  ..., 0.4824, 0.4824, 0.4824],
           [0.4824, 0.4824, 0.4824,  ..., 0.4824, 0.4824, 0.4824],
           [0.4824, 0.4824, 0.4824,  ..., 0.4824, 0.4824, 0.4824]],
 
          [[0.1451, 0.1255, 0.0353,  ..., 0.0118, 0.0000, 0.0000],
           [0.0353, 0.0824, 0.0314,  ..., 0.0000, 0.0196, 0.0000],
           [0.0000, 0.06

In [9]:
batch["resized_shape"], 
# batch["resized_shape"].shape

(((640, 640), (640, 640), (640, 640), (640, 640)),)

In [10]:
batch["ori_shape"], 
# batch["ori_shape"].shape

(((425, 640), (480, 640), (428, 640), (426, 640)),)

In [11]:
batch["bboxes"], batch["bboxes"].shape

(tensor([[0.6186, 0.3745, 0.7628, 0.7140],
         [0.4313, 0.2478, 0.8626, 0.4956],
         [0.4313, 0.7958, 0.8626, 0.4084],
         [0.3625, 0.2342, 0.6820, 0.4684],
         [0.3625, 0.7696, 0.6820, 0.4607],
         [0.4815, 0.0830, 0.1912, 0.1660],
         [0.1489, 0.1900, 0.1174, 0.0491],
         [0.9770, 0.0830, 0.0440, 0.1660],
         [0.7180, 0.1900, 0.1174, 0.0491],
         [0.3160, 0.5212, 0.5438, 0.2542],
         [0.4623, 0.3327, 0.2839, 0.2033],
         [0.4057, 0.5400, 0.2812, 0.2179],
         [0.2363, 0.4060, 0.3863, 0.3336],
         [0.4112, 0.2838, 0.0672, 0.0414],
         [0.4831, 0.2826, 0.0516, 0.0415],
         [0.4234, 0.3241, 0.0747, 0.0627],
         [0.4090, 0.2610, 0.0843, 0.0632],
         [0.8061, 0.5212, 0.3858, 0.2542],
         [0.9442, 0.3327, 0.1096, 0.2033],
         [0.9166, 0.5400, 0.1649, 0.2179],
         [0.8054, 0.4060, 0.3863, 0.3336],
         [0.9729, 0.2838, 0.0523, 0.0414],
         [0.9771, 0.3241, 0.0438, 0.0627],
         [0

In [12]:
batch["cls"], batch["cls"].shape

(tensor([[22.],
         [22.],
         [22.],
         [22.],
         [22.],
         [23.],
         [23.],
         [23.],
         [23.],
         [45.],
         [45.],
         [50.],
         [45.],
         [49.],
         [49.],
         [49.],
         [49.],
         [45.],
         [45.],
         [50.],
         [45.],
         [49.],
         [49.],
         [49.]]),
 torch.Size([24, 1]))